### ISSUE TITLE
Sign Up workflow changes to support Mentors & future users

### ISSUE THREAD

**Issue by suhas2** [job-hax/frontend#143]
Instead of taking users to a new page, open a modal UI with Sign Up interface:
![image](https://user-images.githubusercontent.com/8302550/58744154-286c7980-83f3-11e9-80a9-90917fba5ff9.png)

Instead of Sign Up button, we will have "Next" button:
![image](https://user-images.githubusercontent.com/8302550/58744181-be080900-83f3-11e9-980b-e949787a827e.png)

When user clicks "Next":
![image](https://user-images.githubusercontent.com/8302550/58744255-02e06f80-83f5-11e9-9e39-8b89151dd9f9.png)

Clicks "Next" again:
![image](https://user-images.githubusercontent.com/8302550/58753510-fc91d800-8474-11e9-99d9-44a3364b043c.png)

Clicks University:
![image](https://user-images.githubusercontent.com/8302550/58753948-44682d80-847c-11e9-9283-d6c3936ea8f2.png)

Clicks Student:
![image](https://user-images.githubusercontent.com/8302550/58753995-091a2e80-847d-11e9-9e67-ffd163ff2e0a.png)

Next Step:
![image](https://user-images.githubusercontent.com/8302550/58744395-ffe67e80-83f6-11e9-8a16-dd5c8ce99041.png)

Last Step:
![image](https://user-images.githubusercontent.com/8302550/58754060-d91f5b00-847d-11e9-90fd-6434a4f20021.png)

Click Finish to take user to profile page as we currently do.

**Comment by sakomws** [comment]
awesome bro! @suhas2

**Comment by EgemenUslu** [comment]
done
