### ISSUE TITLE
Job cards are getting cut when list is full on dashboard

### ISSUE THREAD

**Issue by suhas2** [job-hax/frontend#148]
Have the list of cards be the full height of the dashboard, they seem to be getting cut off 3/4th way down.

![image](https://user-images.githubusercontent.com/8302550/59006621-c8e9e180-87d7-11e9-8123-06d8d3a5edc1.png)

**Comment by EgemenUslu** [comment]
Lets talk about this issue on slack, it is more complicated issue than it seems because card heights are dynamic and user screens have different resolutions.

**Comment by EgemenUslu** [comment]
issue is not relevant after the new dashboard design
