### ISSUE TITLE
Notes UX for job cards should be updated. Textbox should be clickable to make changes & save. See comment.

### ISSUE THREAD

**Issue by suhas2** [job-hax/frontend#33]
![image](https://user-images.githubusercontent.com/8302550/54884911-b6e0df80-4e33-11e9-8aca-72a8770edd7e.png)

**Comment by suhas2** [comment]
@EgemenUslu Textbox looks perfect. I think it would be better to just remove the "add a note" button & just show the above textbox directly instead of having to click on the button.

**Comment by EgemenUslu** [comment]
@suhas2 you mean like having an “+Add note” clickable text all above of the notes and when click it opening the bigger text box?

**Comment by suhas2** [comment]
not like that, let me get you an image

**Comment by suhas2** [comment]
Something like this, so its just ready to be typed in:

![image](https://user-images.githubusercontent.com/8302550/55282932-f6b03700-530b-11e9-927e-29a009fb5da0.png)

**Comment by EgemenUslu** [comment]
I see, and it will always be in that size or will be short at first and get longer when clicked? And there wont be “you dont have any note” statement when there is note, right?
