### ISSUE TITLE
Remove extra side coloring when you drag job cards

### ISSUE THREAD

**Issue by suhas2** [job-hax/frontend#48]
![image](https://user-images.githubusercontent.com/8302550/55282780-c2874700-5308-11e9-8183-0250844340f8.png)

**Comment by dhruvarora93** [comment]
Can somebody explain more about this issue? This is not very clear. A screen recording will be helpful. This is one handy tool to create recordings: https://www.useloom.com

**Comment by EgemenUslu** [comment]
@dhruvarora93 it is like that on both firefox and safari,  it shall be like that on chrome too:
https://www.useloom.com/share/dacdcead6e8a481ca9897b3960948593

on chrome it is like that:
https://www.useloom.com/share/98337a85521340129da9802a74901ba3

**Comment by EgemenUslu** [comment]
fixed
