### ISSUE TITLE
Show company logos instead of jobhax icons for job cards

### ISSUE THREAD

**Issue by suhas2** [job-hax/frontend#49]

**Comment by EgemenUslu** [comment]
@suhas2 we are showing jobhax logo when we don’t have company logo. We just have company logos for the applications done via LinkedIn. Shall we keep doing this or what is your suggestion?

**Comment by suhas2** [comment]
It is not showing up for me. I applied everything through LinkedIn:

![image](https://user-images.githubusercontent.com/8302550/55282901-43474280-530b-11e9-820b-d225133b34a9.png)

**Comment by suhas2** [comment]
Also, you can use this: https://clearbit.com/logo. It is free & is not limited to only applications done via LinkedIn.

**Comment by EgemenUslu** [comment]
@suhas2 I dont know why they dont have their own logo, probably their links either are not coming from backend or broken. On the other hand, clearbit.com sound really good, we may get almost all logos from there. I ll connect it.

**Comment by EgemenUslu** [comment]
@hellsayenci, I guess backend shall handle taking source urls from clearbit api and add them to get_jobapps response.  Can you create an issue for that?
