### ISSUE TITLE
Job Card Title defaulting to static text

### ISSUE THREAD

**Issue by suhas2** [job-hax/frontend#61]
https://gyazo.com/0ef0a21709da96758edaba8a28977a2b

**Comment by BabayevAli** [comment]
I think there doesn't need change

**Comment by suhas2** [comment]
We should not be showing static text, it should be Job Title & Company Name. Please see following image:

![image](https://user-images.githubusercontent.com/8302550/55657111-0fa66580-57ae-11e9-82f4-494e66d99063.png)
